cat /srv/docker-compose.yml 
version: "3.8"

x-service_defaults: &service_defaults
    expose: 
      - "80"
    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/hc/ready"]
#      test: "CMD wget --no-verbose --tries=1 --spider http://localhost/hc/live || exit 1"
      test: curl --fail http://localhost/hc/ready || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://192.168.0.42:123"
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      rollback_config:
        parallelism: 1
        delay: 10s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        max_failure_ratio: 0.3
        order: start-first

services:
  saleadmin:
    << : *service_defaults
    image: docker.hasti.co/hastim/saleadmin:dev
  saleapp:
    << : *service_defaults
    image: docker.hasti.co/hastim/saleapp:dev
  saleweb:
    << : *service_defaults
    image: docker.hasti.co/hastim/saleweb:dev

